### ISSUE TITLE
Jobs end ok but with warnings "Failed to restore: "/usr/bin/tar" failed with error"

### ISSUE THREAD

**Issue by stronk7** [brokenpip3/setup-bats-libs#18]
Hi,

I was just updating some actions in my workflows away from Node16 (deprecated), and that made me move from `amdilabs/setup-bats@v1` (not much maintained)  to your awesome `brokenpip3/setup-bats-libs@1.5.2`.

And, while the bats tests in the project are passing ok, I'm getting 4 warnings (related to `tar` problems) for every job in our matrix.

Curiously, I think that the problem doesn't happen on initial executions, but later, when there is stuff cached and the action tries to restore it. Note I may be wrong, but looking to the raw logs... that seems to be the issue.

For reference, here it's a job with 4 matrix elements, each one getting the `tar` warnings 4 times (note it's still running at the time of writing this):

https://github.com/moodlehq/moodle-local_ci/actions/runs/6877757547

Ciao :-)

**Comment by brokenpip3** [comment]
hey!

thanks! I'm glad that my action is used in the moodle project :)

Coming to your questions is a well know issue with the official cache action while you are try to cache/restore files outside the home directory: https://github.com/brokenpip3/setup-bats-libs?tab=readme-ov-file#about-caching

So if you want you can set your libraries to be stored inside the home so it will be cached correctly. For instance in another project I set the action like [this](https://github.com/jenkinsci/kubernetes-operator/blob/63e8a76b95d9a1cf25a68151f031e9702fd7d10a/.github/workflows/auto-tests-bats.yaml#L47-L53) and then load the libraries with the `BATS_LIB_PATH` env [here](https://github.com/jenkinsci/kubernetes-operator/blob/63e8a76b95d9a1cf25a68151f031e9702fd7d10a/.github/workflows/auto-tests-bats.yaml#L62), also [here](https://github.com/jenkinsci/kubernetes-operator/blob/63e8a76b95d9a1cf25a68151f031e9702fd7d10a/test/bats/test_helper.bash#L2).

Let me know if you have other question!

**Comment by stronk7** [comment]
Aha,

thanks for the insight, I'll move them (in fact I think I don't need all them) and will use `BATS_LIB_PATH` as suggested. I had read that section about caching but was unable to connect the points.

Apart from that, just guessing... wouldn't be better to make the default behaviour to be a warnings-free one? Note I've zero idea about GH Actions, heh. But I would expect the action to work without "surprises" by default. Not sure if that implies trying to install in a supported (by caching) place or if it implies to disable caching by default... but for sure any of them would provide a better default experience.

Just sharing my thoughts, will all respects. Thanks for the action and the support!

Ciao :-)

**Comment by brokenpip3** [comment]
>Apart from that, just guessing... wouldn't be better to make the default behaviour to be a warnings-free one? Note I've zero idea about GH Actions, heh. But I would expect the action to work without "surprises" by default. Not sure if that implies trying to install in a supported (by caching) place or if it implies to disable caching by default... but for sure any of them would provide a better default experience.

I decide to not do that 'cause before 1.x of this action (without caching) the default options was using `/usr/lib` so I preferred to leave the time to all the historically users of this action to digest the latest changes of this actions (cache, bats binary etc) and then one day switch the default path to something like `"${{ github.workspace }}/.bats` by default for everyone. 
Maybe from 1/2024 I will change it for good with a deprecation notice :)

**Comment by stronk7** [comment]
All right!

BTW, confirmed that following your recommendation (installing the libraries @ `${{ github.workspace }}/.bats` and setting `BATS_LIB_PATH` to point to it worked and made the reported `tar` warnings to disappear.

Thanks and ciao :-)

**Comment by brokenpip3** [comment]
yw :)
Can we close this issue?

**Comment by stronk7** [comment]
Ah, for me it's ok. 100%
